<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  	<?php 
  		echo $this->headLink()->appendStylesheet('bower_components/svn/include/resources/css/ext-all.css');

  		echo $this->headScript()
  			->appendFile('bower_components/svn/include/ext-all.js')
  			->appendFile('js/app.js');
	?>
	<script>
    Ext.onReady(function() {
        Ext.Loader.setConfig({
            enabled: false
        });

        Ext.application({
            name: 'demo',
            autoCreateViewPort: false,
            launch: function() {
                // Ext.define('demo.myModule.view.Panel', {
                //     extend: 'Ext.panel.Panel',
                //     layout:'fit',
                //     items: {
                //         title: 'Inner Panel',
                //         html: '<p>This panel is fit within its container.</p>',
                //         bodyStyle: 'padding:15px',
                //         border: false
                //     },
                //     renderTo: Ext.getBody()
                // });

                Ext.create('demo.myModule.view.Panel');
            }
        });
    });
	</script>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>ZF Quickstart Application</b>
    </div>
</div>
	<?php echo $this->layout()->content ?>
</body>
</html>